name: gurps_trait_parser_app
description: An app built using Flutter for web
version: 1.0.0+1

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gurps_traits:
    git:
      url: https://github.com/mjeffw/gurps_traits
  dart_utils:
    git:
      url: https://github.com/mjeffw/dart_utils
  flutter_slidable: ^0.5.3
  quiver: ^2.1.2+1
  flutter_typeahead: ^1.6.1

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  pedantic: ^1.7.0

flutter:
  uses-material-design: true
  fonts:
    - family: Muli
      fonts:
        - asset: assets/Muli-Light.ttf
